server:
  port: 8010

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
# SpringBoot日志默认为INFO，调整Feign日志级别为DEBUG，以查看HTTP请示信息
logging:
  level:
    org.alive.springcloudalibaba.order.feign: debug