server:
  port: 8011

spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 192.168.56.101:8848
      discovery:
        username: nacos
        password: nacos
        register-enabled: true
        ip: 10.0.9.31
    sentinel:
      enabled: true
      eager: true
      filter:
        enabled: false
      transport:
        ## 指定控制台的地址
        dashboard: 192.168.56.101:8858

# Feign开启对Sentinel支持
feign:
  sentinel:
    enabled: true