server:
  name: springlab
  port: 8090
  # 1.X的配置方式
  context-path: /springlab
  # 2.X的配置方式
  servlet:
    context-path: /springlab

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/testdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: AaZz1@#45

  redis:
    host: 192.168.56.102
    port: 6379
    password: AaZz1@#4501

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性

logging:
  level:
    org.springframework: INFO